### ISSUE TITLE
Performance issues with SSH via the SDK

### ISSUE THREAD

**Issue by jruckle** [CenturyLinkCloud/clc-java-sdk#198]
@mitullshah as reported that SSH operations via the SDK are a bit slower than other means. Do you have any reason why this would be the case @idrabenia & @s-matyukevich

**Comment by mitullshah** [comment]
Hi,

I have used below reference code to test server connection through SSH. It took around 3 minutes to connect server and just fraction of seconds to run those commands. I tried to connect server through PUTTY and it connects that LINUX box in fraction of seconds that means there is no connection/network issues. Any thoughts?

Sample Code:
OperationFuture<ShellResponse> response = clcSdk.serverService.execSsh(myConfig.serverRef)
	            .run("mkdir test; cd test; mkdir test1; mv test1 testing")
	            .execute()
	            .waitUntilComplete();
		System.out.println("Trace:: "+response.getResult().getTrace());
		System.out.println("Error Status:: "+response.getResult().getErrorStatus());
		System.out.println("Result Readable String:: "+response.getResult().toReadableString());
		System.out.println("Result String:: "+response.getResult().toString());

**Comment by idrabenia** [comment]
Hi @jruckle @mitullshah @KseniaRamaniuk,

Yep, before connect to machine - SDK checks that VM has external IP address with opened SSH port. If machine hasn't external IP - SDK creates it. I think this is a reason of delay that you had - SDK just waiting while CenturyLink Cloud prepare external IP for your machine.

Best Regards,
Ilya

**Comment by mitullshah** [comment]
Hi @idrabenia,

Thanks for your quick response. We have requirement to access VM through internal IP only hence i have modified ServerService.execSsh code  to access the server using internal IP which has SSH port open and now it works properly. Thanks for pointing out root cause.

Is there any specific reason to open SSH port for public IP? Apart from that i have tried multiple runs over one specified machine and it takes around 3 minutes to connect. Any thoughts?

Thanks,
Mitul Shah

**Comment by idrabenia** [comment]
Hi @mitullshah ,

"Is there any specific reason to open SSH port for public IP?"
Yeah, it allow without any specific computer tuning (like network / VPN configuring) connect to server and execute ssh command on it.

"Apart from that i have tried multiple runs over one specified machine and it takes around 3 minutes to connect. Any thoughts?"
Yep, not a problem. We will see. But I think it will be possible to speedup method execution max in 2 times. Because in all cases we need to received server IP (internal or external - it does not make sense) and send a bunch of queries to cloud backend.

Also which is type of reference `myConfig.serverRef` used in you example? Could you provide its declaration? Is it reference by name or by ID? Because in worst case - SDK may load much data from backend and filter start filter it. Best performance you will receive specifying serverRef by ID and datacenter, SDK has special optimisation for load server data for such references by single server request.

Also for our project will be great if you provide some feedback in general if it is not difficult for you.
What do you think about overall SDK design? Is it suitable for your project? Do you have some difficulties in using some SDK APIs / learning SDK docs? 

Thank you!
- Ilya

**Comment by push1st1k** [comment]
Hi @mitullshah,

I've been checked the sample code, you were provided, at the first time the execution by SSH took about 3 min, because, as @idrabenia said, the server should have a public IP and it's added. The code execution for a server with public IP was completed for a ~30 secs. 

Could you please provide the code where you define `myConfig.serverRef` value?

Thank you in advance,
Alex

**Comment by mitullshah** [comment]
Hi,

Below is sample code which tries to connect "NY1MS4HOAPP01" server using server reference (serverRef=Server.refById(serverId)) using Internal IP. I have modified ServerService.execSsh code to use Internal IP to connect server. With below code, it takes just 5 to 10 seconds to connect server and execute commands using Internal IP which took 3 mins to connect server in case of Public IP.:

@Configuration
@EnableClcSdk
public class MyConfig {

	@Bean
	public CredentialsProvider clcCredentialsProvider() {
		return new StaticCredentialsProvider("username", "password");
	}

	@Bean
	public SdkConfiguration clcSdkConfig() {
		return new SdkConfigurationBuilder().build();
	}

	@Autowired
	ServerService serverService;

	@Autowired
	GroupService groupService;
	
	private Server serverRef;
	
	public static void main(String[] args) {
		MyConfig myConfig = new MyConfig();
		CredentialsProvider credentialsProvider = myConfig
				.clcCredentialsProvider();
		System.out.println("Connected User Name:: "+credentialsProvider.getCredentials().getUsername());
		//System.out.println(credentialsProvider.getCredentials().getPassword());

		ClcSdk clcSdk = new ClcSdk(credentialsProvider);
		.....
		String serverId="NY1MS4HOAPP01"; //Server reference
		connectRemoteServerBySSH(clcSdk, myConfig,serverId);
		.....
	}
	private static void connectRemoteServerBySSH(ClcSdk clcSdk, MyConfig myConfig, String serverId){
		myConfig.serverRef=Server.refById(serverId);
		ServerMetadata serverMetadata = clcSdk.serverService().findByRef(myConfig.serverRef);
		....
		ServerCredentials credentials = clcSdk.serverClient.getServerCredentials(serverMetadata.getName());
		....
		OperationFuture<ShellResponse> response = clcSdk.serverService.execSsh(myConfig.serverRef)
	            .run("mkdir mitul; cd mitul; mkdir test; mv test testing")
	            .execute()
	            .waitUntilComplete();
		
		System.out.println("Trace:: "+response.getResult().getTrace());
		System.out.println("Error Status:: "+response.getResult().getErrorStatus());
		System.out.println("Result Readable String:: "+response.getResult().toReadableString());
		System.out.println("Result String:: "+response.getResult().toString());
		
	}	
	
}


public class ServerService implements QueryService<Server, ServerFilter, ServerMetadata> {
......

public SshClient execSsh(Server server) {
        checkNotNull(server);

        ServerMetadata metadata = findByRef(server);
		//Commented to use Internal IP to connect server.
        /*if (!findPublicIpWithOpenSshPort(server).isPresent()) {
            this
                .addPublicIp(server, new CreatePublicIpConfig().openPorts(SSH))
                .waitUntilComplete();
        }

        Optional<String> publicIp = findPublicIpWithOpenSshPort(server);*/
        
        String internalIPAddress=null;
        String externalIPAddress=null;
        for (com.centurylink.cloud.sdk.server.services.client.domain.server.IpAddress ipAddress : metadata
				.getDetails().getIpAddresses()) {
        	internalIPAddress=ipAddress.getInternal();
        	System.out.println("Server Internal Ip:: "
					+ internalIPAddress);
        	externalIPAddress=ipAddress.getPublicIp();
			System.out.println("Server Public Ip:: "
					+ externalIPAddress);
			
		}

        ServerCredentials serverCredentials = client.getServerCredentials(metadata.getId());
        return new SshjClient.Builder()
                .username(serverCredentials.getUserName())
                .password(serverCredentials.getPassword())
                //.host(publicIp.get())
                .host(internalIPAddress)
                .build();
    }
.....
}		

Thanks,
Mitul Shah

**Comment by push1st1k** [comment]
Hi @mitullshah,

I've tried to launch the code one more time for a server in NY1 DC and I got the same results. 
1st time ~3min


Could you please modify a little bit the original code?

```java
public class ServerService implements QueryService ...
...
    public SshClient execSsh(Server server) {
        checkNotNull(server);

        System.out.println("load metadata " + new Date());
        ServerMetadata metadata = findByRef(server);

        if (!findPublicIpWithOpenSshPort(server).isPresent()) {
            System.out.println("add public ip " + new Date());
            this
                .addPublicIp(server, new CreatePublicIpConfig().openPorts(SSH))
                .waitUntilComplete();
        }
        System.out.println("get public ip " + new Date());
        Optional<String> publicIp = findPublicIpWithOpenSshPort(server);

        System.out.println("get credentials " + new Date());
        ServerCredentials serverCredentials = client.getServerCredentials(metadata.getId());

        System.out.println("build ssh client " + new Date());
        return new SshjClient.Builder()
                .username(serverCredentials.getUserName())
                .password(serverCredentials.getPassword())
                .host(publicIp.get())
                .build();
    }
```

```java
public class MyConfig {
...
private static void connectRemoteServerBySSH(ClcSdk clcSdk, MyConfig myConfig, String serverId){
    myConfig.serverRef=Server.refById(serverId);
    System.out.println("main | get metadata " + new Date());
    ServerMetadata serverMetadata = clcSdk.serverService().findByRef(myConfig.serverRef);
    ....
    System.out.println("main | get credentials " + new Date());
    ServerCredentials credentials = clcSdk.serverClient.getServerCredentials(serverMetadata.getName());
    ....
    System.out.println("main | exec " + new Date());
    OperationFuture<ShellResponse> response = clcSdk.serverService.execSsh(myConfig.serverRef)
            .run("mkdir mitul; cd mitul; mkdir test; mv test testing")
            .execute()
            .waitUntilComplete();

    System.out.println("main | done " + new Date());
    System.out.println("Trace:: "+response.getResult().getTrace());
    System.out.println("Error Status:: "+response.getResult().getErrorStatus());
    System.out.println("Result Readable String:: "+response.getResult().toReadableString());
    System.out.println("Result String:: "+response.getResult().toString());

}   
```

I've added logging the time between method calls. It may help to identify the piece of code that has big latency.

Thank you,
Alex

**Comment by mitullshah** [comment]
Hi @push1st1k 

As mentioned earlier, 3 minutes time is for execution of following code:

OperationFuture<ShellResponse> response = clcSdk.serverService.execSsh(myConfig.serverRef)
            .run("mkdir mitul; cd mitul; mkdir test; mv test testing")
            .execute()
            .waitUntilComplete();

In which, findPublicIpWithOpenSshPort(server) is taking more time to check and open Public IP with SSH (22). Right now, i can't run execSsh with Public IP because it will open Public IP with SSH (22) unnecessary on my running server which is in use by team.

Thanks,
Mitul Shah

**Comment by push1st1k** [comment]
Hi @mitullshah 

This issue was fixed, please refer to [wiki](https://github.com/CenturyLinkCloud/clc-java-sdk/wiki/2.3-Configuring-remote-servers-over-SSH) and check that all works as expected.

Thanks,
Alex
